name: Salesforce Authentication and Test Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auth-and-test-salesforce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI (new @salesforce/cli)
        run: npm install --global @salesforce/cli

      - name: Write JWT Key from Secret
        run: echo "${{ secrets.SF_JWT_KEY }}" > server.key

      - name: Authenticate to Salesforce using JWT
        run: |
          sf org login jwt \
            --client-id ${{ secrets.SF_CLIENT_ID }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instance-url ${{ secrets.SF_ORG_URL }} \
            --set-default \
            --alias my-org

      - name: Confirm authentication
        run: sf org list

      - name: Run all Apex tests
        run: |
          sf apex test run --test-level RunLocalTests --result-format human --output-dir test-results --wait 10 --target-org my-org

      - name: Check test results
        run: |
          if grep -q "Fail" test-results/test-result.txt; then
            echo "Some tests failed."
            exit 1
          else
            echo "All tests passed."
          fi
