name: Salesforce Authentication

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auth-salesforce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI (new @salesforce/cli)
        run: npm install --global @salesforce/cli

      - name: Write JWT Key from Secret
        run: echo "${{ secrets.SF_JWT_KEY }}" > server.key

      - name: Authenticate to Salesforce using JWT
        run: |
          sf org login jwt \
            --client-id ${{ secrets.SF_CLIENT_ID }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME }} \
            --instance-url ${{ secrets.SF_INSTANCE_URL }} \
            --set-default \
            --alias my-org

      - name: Confirm authentication
        run: sf org list
